version: '3.8'

services:
  tv-scrapper-mysql-db:
    container_name: tv-scrapper-mysql-db
    image: mysql:8.0.32
    ports:
      - '${TV_SCRAPPER_MYSQL_PORT}:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${TV_SCRAPPER_MYSQL_PASSWORD}'
      - 'MYSQL_DATABASE=aggregator-db'
    volumes:
      - ./.volumes/mysql/mysql-volume:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -u root -p$root"
    networks:
      - tv-scrapper-network

  tv-scrapper-data-server:
    container_name: tv-scrapper-data-server
    ports:
      - '${TV_SCRAPPER_DATA_SERVER_PORT}:4361'
    build:
      context: ./data-server
      dockerfile: Dockerfile
    environment:
      - 'DB_HOST=tv-scrapper-mysql-db'
      - 'DB_PORT=3306'
      - 'DB_NAME=aggregator-db'
      - 'DB_USERNAME=root'
      - 'DB_PASSWORD=${TV_SCRAPPER_MYSQL_PASSWORD}'
    networks:
      - tv-scrapper-network

  tv-scrapper-web-ui:
    container_name: tv-scrapper-web-ui
    ports:
      - '${TV_SCRAPPER_WEB_UI_PORT}:80'
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    networks:
      - tv-scrapper-network

networks:
  tv-scrapper-network:
    driver: bridge