server:
  port: 4361

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

app-properties:
  client-urls:
    - http://localhost:4362
    - http://tv-web-ui:4362
