server:
  port: 4361

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

app-properties:
  client-urls:
    - http://localhost:4362
    - http://tv-web-ui:4362
  chart-colors:
    - '#a6cee3'
    - '#1f78b4'
    - '#b2df8a'
    - '#33a02c'
    - '#fb9a99'
    - '#e31a1c'
    - '#fdbf6f'
    - '#ff7f00'
    - '#cab2d6'
    - '#6a3d9a'
    - '#ffff99'
    - '#b15928'
  default-chart-color: '#d3d3d3'
